# Generated by Django 4.1 on 2022-08-27 15:20

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Social_Media_App', '0003_alter_profile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='posting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='posting_images')),
                ('caption', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
