# Generated by Django 4.1 on 2022-08-31 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social_Media_App', '0006_followerscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='working',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
