# Generated by Django 4.0.7 on 2022-10-10 16:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('date_created', models.DateTimeField(auto_created=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_last_modified', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=64)),
                ('tag_use_counter', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'tags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('calling_code', models.CharField(blank=True, max_length=4, null=True)),
                ('country_code', models.CharField(blank=True, max_length=3, null=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('date_last_modified', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('account_verified', models.BooleanField(default=False)),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='image')),
                ('current_city', models.CharField(blank=True, max_length=255, null=True)),
                ('date_last_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('edu_institution', models.CharField(blank=True, max_length=128, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=False)),
                ('follower_count', models.IntegerField(default=0)),
                ('following_count', models.IntegerField(default=0)),
                ('gender', models.CharField(blank=True, choices=[('1', 'None'), ('2', 'Male'), ('3', 'Female'), ('4', 'Transgender')], default='1', max_length=16)),
                ('hometown', models.CharField(blank=True, max_length=255, null=True)),
                ('intro', models.TextField(blank=True, max_length=300, null=True)),
                ('join_date', models.DateTimeField(blank=True, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='image')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('role', models.CharField(max_length=32)),
                ('workplace', models.CharField(blank=True, max_length=128, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='my_social_app.countries')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
