# Generated by Django 4.0.7 on 2022-10-10 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_social_app', '0002_comment_post_tag_posttag_postlike_followusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='shared_post',
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='liker',
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='post',
        ),
        migrations.RemoveField(
            model_name='posttag',
            name='post',
        ),
        migrations.RemoveField(
            model_name='posttag',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='PostLike',
        ),
        migrations.DeleteModel(
            name='PostTag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
