# Generated by Django 4.0.7 on 2022-10-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_social_app', '0003_remove_post_author_remove_post_shared_post_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('date_last_modified', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('tag_use_counter', models.IntegerField(default=0)),
            ],
        ),
    ]
