# Generated by Django 4.1 on 2022-10-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_social_app', '0005_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Transgender'), ('3', '')], default='1', max_length=16),
        ),
    ]
