# Generated by Django 4.0.7 on 2022-10-10 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_social_app', '0006_postlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_social_app.post')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_social_app.tag')),
            ],
        ),
    ]
