# Generated by Django 4.0.7 on 2022-10-10 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_social_app', '0007_posttag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, max_length=1024, null=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('date_last_modified', models.DateTimeField(blank=True, null=True)),
                ('like_count', models.IntegerField(blank=True, default=0, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_social_app.post')),
            ],
        ),
    ]
