# Generated by Django 4.1 on 2022-10-10 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_social_app', '0007_alter_user_account_verified_and_more'),
        ('my_social_app', '0008_alter_user_gender'),
    ]

    operations = [
    ]
