# Generated by Django 4.1 on 2022-10-11 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_social_app', '0010_commentlikes'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='countries',
            table=None,
        ),
    ]
