# Generated by Django 4.1 on 2022-10-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_social_app', '0011_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to=''),
        ),
    ]
