# Generated by Django 4.1 on 2022-10-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_social_app', '0012_alter_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('1', 'None'), ('2', 'Male'), ('3', 'Female'), ('4', 'Transgender')], default='1', max_length=16),
        ),
    ]
