# Generated by Django 4.1 on 2022-10-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_social_app', '0013_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='follower_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='following_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='hometown',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='intro',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
