# Generated by Django 4.1 on 2022-10-11 08:26

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('my_social_app', '0013_remove_countries_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='name',
            field=django_countries.fields.CountryField(default=0, max_length=2),
            preserve_default=False,
        ),
    ]
