# Generated by Django 4.1 on 2022-10-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_social_app', '0014_alter_user_follower_count_alter_user_following_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
