# Generated by Django 4.1 on 2022-10-11 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_social_app', '0014_countries_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countries',
            name='calling_code',
        ),
        migrations.RemoveField(
            model_name='countries',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='countries',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='countries',
            name='date_last_modified',
        ),
    ]
