# Generated by Django 4.1 on 2022-10-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_social_app', '0015_alter_user_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='intro',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
