# Generated by Django 4.1 on 2022-10-14 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_social_app', '0015_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 14, 18, 53, 26, 160032)),
        ),
    ]
