# Generated by Django 4.1 on 2022-10-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_social_app', '0016_alter_user_current_city_alter_user_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
