# Generated by Django 4.1 on 2022-10-14 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_social_app', '0020_alter_post_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 14, 19, 4, 16, 833799)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_last_modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
