# Generated by Django 4.1 on 2022-10-14 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_social_app', '0021_alter_post_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 14, 19, 11, 30, 922682)),
        ),
    ]
