# Generated by Django 4.0.7 on 2022-10-14 18:25

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_social_app', '0024_alter_post_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='my_social_app.tag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 14, 23, 55, 47, 730026)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_last_modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 14, 23, 55, 47, 730026)),
        ),
        migrations.AlterField(
            model_name='tag',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 14, 23, 55, 47, 731046)),
        ),
        migrations.AlterField(
            model_name='tag',
            name='date_last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
