# Generated by Django 4.0.7 on 2022-10-14 18:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_social_app', '0033_alter_post_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
