# Generated by Django 4.0.7 on 2022-10-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_social_app', '0034_alter_post_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_tag',
            field=models.ManyToManyField(to='my_social_app.tag'),
        ),
    ]
