# Generated by Django 4.0.7 on 2022-10-14 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_social_app', '0035_alter_post_post_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='comment_count',
            new_name='commentCount',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date_created',
            new_name='dateCreated',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date_last_modified',
            new_name='dateLastModified',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='is_type_share',
            new_name='isTypeShare',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='like_count',
            new_name='likeCount',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_photo',
            new_name='postPhoto',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_tag',
            new_name='postTags',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='share_count',
            new_name='shareCount',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='shared_post',
            new_name='sharedPost',
        ),
    ]
