# Generated by Django 4.0.7 on 2022-10-14 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_social_app', '0036_rename_comment_count_post_commentcount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='date_created',
            new_name='dateCreated',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='date_last_modified',
            new_name='dateLastModified',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='tag_use_counter',
            new_name='tagUseCounter',
        ),
    ]
