# Generated by Django 4.0.7 on 2022-10-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_social_app', '0038_alter_post_commentcount_alter_post_likecount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='isTypeShare',
            field=models.BooleanField(default=False),
        ),
    ]
