# Generated by Django 4.1 on 2022-10-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_social_app', '0041_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postPhoto',
            field=models.ImageField(blank=True, default='image/images_1.jpeg', null=True, upload_to='image'),
        ),
    ]
