# Generated by Django 4.1 on 2022-10-18 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_social_app', '0045_rename_datecreated_comment_date_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date_created',
            new_name='dateCreated',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='date_last_modified',
            new_name='dateLastModified',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='like_count',
            new_name='likeCount',
        ),
    ]
