# Generated by Django 4.1 on 2022-10-18 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_social_app', '0047_alter_notification_date_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='date_created',
            new_name='dateCreated',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='date_last_modified',
            new_name='dateLastModified',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='date_updated',
            new_name='dateUpdated',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='is_read',
            new_name='isRead',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='is_seen',
            new_name='isSeen',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='owning_comment',
            new_name='owningComment',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='owning_post',
            new_name='owningPost',
        ),
    ]
