# Generated by Django 4.1.2 on 2022-10-26 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_social_app', '0050_threads_threadchatmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='body',
            new_name='message',
        ),
    ]
