# Generated by Django 4.1.2 on 2022-10-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_social_app', '0051_rename_body_chatmessage_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='seen',
        ),
        migrations.AddField(
            model_name='threadchatmessage',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
