# Generated by Django 4.1 on 2022-10-10 07:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('calling_code', models.CharField(blank=True, max_length=4, null=True)),
                ('country_code', models.CharField(blank=True, max_length=3, null=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('date_last_modified', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'db_table': 'countries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('account_verified', models.TextField(blank=True, null=True)),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('cover_photo', models.CharField(blank=True, max_length=256, null=True)),
                ('current_city', models.CharField(blank=True, max_length=128, null=True)),
                ('date_last_modified', models.DateTimeField(blank=True, null=True)),
                ('edu_institution', models.CharField(blank=True, max_length=128, null=True)),
                ('email_verified', models.TextField(blank=True, null=True)),
                ('enabled', models.TextField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=64)),
                ('follower_count', models.IntegerField(blank=True, null=True)),
                ('following_count', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=16, null=True)),
                ('hometown', models.CharField(blank=True, max_length=128, null=True)),
                ('intro', models.CharField(blank=True, max_length=100, null=True)),
                ('join_date', models.DateTimeField(blank=True, null=True)),
                ('last_name', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=256)),
                ('profile_photo', models.CharField(blank=True, max_length=256, null=True)),
                ('role', models.CharField(max_length=32)),
                ('workplace', models.CharField(blank=True, max_length=128, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
